; loop test, AKG format, v1.0.

; Generated by Arkos Tracker 2.

looptest_Start
looptest_StartDisarkGenerateExternalLabel

looptest_DisarkByteRegionStart0
	db "AT20"
looptest_DisarkPointerRegionStart1
	dw looptest_ArpeggioTable	; The address of the Arpeggio table.
	dw looptest_PitchTable	; The address of the Pitch table.
	dw looptest_InstrumentTable	; The address of the Instrument table.
	dw looptest_EffectBlockTable	; The address of the Effect Block table.
looptest_DisarkPointerRegionEnd1


; The addresses of each Subsong:
looptest_DisarkPointerRegionStart2
	dw looptest_Subsong0_Start
looptest_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
looptest_ArpeggioTable
looptest_DisarkPointerRegionStart3
looptest_DisarkPointerRegionEnd3

; Declares all the Pitches.
looptest_PitchTable
looptest_DisarkPointerRegionStart4
looptest_DisarkPointerRegionEnd4

; Declares all the Instruments.
looptest_InstrumentTable
looptest_DisarkPointerRegionStart5
	dw looptest_EmptyInstrument
	dw looptest_Instrument1
	dw looptest_Instrument2
	dw looptest_Instrument3
	dw looptest_Instrument4
	dw looptest_Instrument5
looptest_DisarkPointerRegionEnd5

looptest_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
looptest_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

looptest_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 3	; Noise: 3.

	db 105	; Soft only. Volume: 13.
	db 36	; Additional data. Noise: 4. Pitch? true. Arp? false. Period? false.
	dw 80	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 400	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1280	; Pitch.

	db 6	; Loop to silence.

looptest_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 75	; Additional data. Noise: 11. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 74	; Additional data. Noise: 10. Pitch? false. Arp? true. Period? false.
	db 13	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 73	; Additional data. Noise: 9. Pitch? false. Arp? true. Period? false.
	db 16	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 72	; Additional data. Noise: 8. Pitch? false. Arp? true. Period? false.
	db 9	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 7	; Additional data. Noise: 7. Pitch? false. Arp? false. Period? false.

	db 81	; Soft only. Volume: 10.
	db 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	db 9	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 69	; Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	db 14	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 4	; Additional data. Noise: 4. Pitch? false. Arp? false. Period? false.

	db 33	; Soft only. Volume: 4.
	db 3	; Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	db 25	; Soft only. Volume: 3.
	db 2	; Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	db 6	; Loop to silence.

looptest_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 240	; No Soft no Hard. Volume: 14. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 224	; No Soft no Hard. Volume: 12. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 152	; No Soft no Hard. Volume: 3. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

looptest_Instrument4
	db 8	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

looptest_Instrument4_Loop	db 241	; Soft only. Volume: 14. Volume only.

	db 7	; Loop.
looptest_DisarkWordForceReference6
	dw looptest_Instrument4_Loop	; Loop here.

looptest_Instrument5
	db 8	; The speed (>0, 0 for 256).
looptest_Instrument5_Loop	db 249	; Soft only. Volume: 15. Volume only.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 7	; Loop.
looptest_DisarkWordForceReference7
	dw looptest_Instrument5_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
looptest_EffectBlockTable
looptest_DisarkPointerRegionStart8
	dw looptest_EffectBlock_P4P3	; Index 0
	dw looptest_EffectBlock_P4P2	; Index 1
	dw looptest_EffectBlock_P4P0	; Index 2
	dw looptest_EffectBlock_P4P4	; Index 3
	dw looptest_EffectBlock_P4P5	; Index 4
	dw looptest_EffectBlock_P4P6	; Index 5
	dw looptest_EffectBlock_P4P7	; Index 6
	dw looptest_EffectBlock_P4P8	; Index 7
	dw looptest_EffectBlock_P4P9	; Index 8
	dw looptest_EffectBlock_P4P10	; Index 9
	dw looptest_EffectBlock_P4P11	; Index 10
	dw looptest_EffectBlock_P4P12	; Index 11
	dw looptest_EffectBlock_P4P13	; Index 12
	dw looptest_EffectBlock_P4P14	; Index 13
	dw looptest_EffectBlock_P4P15	; Index 14
looptest_DisarkPointerRegionEnd8

looptest_EffectBlock_P4P0
	db 4, 0
looptest_EffectBlock_P4P2
	db 4, 2
looptest_EffectBlock_P4P3
	db 4, 3
looptest_EffectBlock_P4P4
	db 4, 4
looptest_EffectBlock_P4P5
	db 4, 5
looptest_EffectBlock_P4P6
	db 4, 6
looptest_EffectBlock_P4P7
	db 4, 7
looptest_EffectBlock_P4P8
	db 4, 8
looptest_EffectBlock_P4P9
	db 4, 9
looptest_EffectBlock_P4P10
	db 4, 10
looptest_EffectBlock_P4P11
	db 4, 11
looptest_EffectBlock_P4P12
	db 4, 12
looptest_EffectBlock_P4P13
	db 4, 13
looptest_EffectBlock_P4P14
	db 4, 14
looptest_EffectBlock_P4P15
	db 4, 15

looptest_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
looptest_Subsong0_DisarkByteRegionStart0
looptest_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 2	; Loop start index (>=0).
	db 3	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 0	; Base note index (>=0).

looptest_Subsong0_Linker
looptest_Subsong0_DisarkPointerRegionStart1
; Position 0
	dw looptest_Subsong0_Track2
	dw looptest_Subsong0_Track1
	dw looptest_Subsong0_Track0
	dw looptest_Subsong0_LinkerBlock0

; Position 1
	dw looptest_Subsong0_Track3
	dw looptest_Subsong0_Track4
	dw looptest_Subsong0_Track5
	dw looptest_Subsong0_LinkerBlock0

; Position 2
looptest_Subsong0_Linker_Loop
	dw looptest_Subsong0_Track6
	dw looptest_Subsong0_Track7
	dw looptest_Subsong0_Track8
	dw looptest_Subsong0_LinkerBlock0

; Position 3
	dw looptest_Subsong0_Track6
	dw looptest_Subsong0_Track7
	dw looptest_Subsong0_Track9
	dw looptest_Subsong0_LinkerBlock0

looptest_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
looptest_Subsong0_DisarkWordForceReference2
	dw looptest_Subsong0_Linker_Loop

looptest_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
looptest_Subsong0_DisarkWordForceReference3
	dw looptest_Subsong0_SpeedTrack0	; SpeedTrack address.
looptest_Subsong0_DisarkWordForceReference4
	dw looptest_Subsong0_EventTrack0	; EventTrack address.

looptest_Subsong0_Track0
	db 218
	db 5	; New Instrument (5).
	db 9	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 117
	db 8	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 102
	db 7	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 90
	db 6	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 102
	db 5	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 107
	db 4	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 117
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 104
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track1
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track2
	db 218
	db 4	; New Instrument (4).
	db 14	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 102
	db 13	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 102
	db 12	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 102
	db 11	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 90
	db 10	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 102
	db 9	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 93
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 105
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 109
	db 6	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 102
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 90
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 83
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 95
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track3
	db 218
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track4
	db 228
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 176
	db 3	; New Instrument (3).
	db 61, 14	; Waits for 15 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 164
	db 1	; New Instrument (1).
	db 61, 14	; Waits for 15 lines.

	db 176
	db 3	; New Instrument (3).
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track5
	db 218
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 6	; Waits for 7 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track6
	db 218
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 36
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track7
	db 228
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 176
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 166
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 176
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 60	; Waits for 1 line.

	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 166
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 176
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 166
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track8
	db 237
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 61, 127	; Waits for 128 lines.


looptest_Subsong0_Track9
	db 237
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


; The speed tracks
looptest_Subsong0_SpeedTrack0
	db 10	; Value: 5.
	db 253	; Wait for 127 lines.

; The event tracks
looptest_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

looptest_Subsong0_DisarkByteRegionEnd0
